from __future__ import annotations

import re

from playwright.async_api import (
    TimeoutError as PlaywrightTimeoutError,
)
from playwright.async_api import (
    async_playwright,
)
from selectolax.parser import HTMLParser, Node

from book_alerter.db.models import Book, Condition
from book_alerter.sources.base import (
    ObservationCandidate,
    SourceError,
)
from book_alerter.sources.condition_normalizers import condition_from_grade_text
from book_alerter.sources.inline_source import InlineSource
from book_alerter.sources.normalizers import amazon_uk_dp_url, asin_for_amazon_uk

# Amazon UK is fronted by aggressive bot-protection that defeats any client
# that doesn't render JS in a real browser (verified 2026-05-14: headless
# Chromium + stealth flags + cookie warm-up still got served the
# "To discuss automated access to Amazon" interstitial). So this source
# drives headless Chromium via Playwright for every lookup.
#
# Strategy: try /dp/<ISBN> first to extract the buy-box price. If the dp
# page has no usable buy-box (out of stock, marketplace-only listing,
# etc.), fall back to /gp/offer-listing/<ISBN>?condition=all and enumerate
# the marketplace offers.
#
# Region: UK only at MVP. Pass region="UK" or accept the default.
#
# DOM contract:
#   dp page          - buy-box price under #corePriceDisplay_desktop_feature_div
#                      OR #corePrice_feature_div. Within, .a-price wraps the
#                      number; .a-offscreen carries the screen-reader-friendly
#                      full price ("£7.99"). Prefer .a-offscreen — it's the
#                      most stable selector.
#   offer-listing    - rows under #aod-offer-list, each `#aod-offer` (modern
#                      AOD layout). Legacy fallback: `.olpOffer`. Within each
#                      row: #aod-offer-price (.a-offscreen), #aod-offer-shipping,
#                      #aod-offer-heading (h5 text with the condition),
#                      #aod-offer-soldBy (seller link text).

# Tolerates "£7.99" / "&pound;7.99" / "7.99" — whichever DOM branch we end
# up reading.
_PRICE_NUMERIC_RE = re.compile(r"(\d+(?:\.\d{1,2})?)")

# Fallback path for the dp buy-box price. Amazon's inline JS state embeds
# the current selling price as `"priceAmount":34.52` somewhere in the
# HTML body, ahead of any "lowest used/new from £X" sub-prices. selectolax
# CSS scraping of `.a-price .a-offscreen` is unreliable on this page —
# Amazon's React hydration moves the actual buy-box element around between
# initial render and post-hydration, so the static HTML selectolax sees
# doesn't always contain the visible buy-box price under the expected
# corePriceDisplay scope. The priceAmount field is generated by Amazon's
# pricing service and reflects the same number rendered to the user.
_PRICE_AMOUNT_RE = re.compile(r'"priceAmount"\s*:\s*(\d+(?:\.\d{1,2})?)')

# Amazon UK indexes books by ISBN-10 (which IS the ASIN for books). The /dp
# and /gp/offer-listing URLs only resolve to a real product page when the path
# segment is the ISBN-10. /dp/{ISBN-13} silently serves a generic ~2 KB "Page
# Not Found" instead of redirecting — the page still contains Amazon's
# standard footer copy ("To discuss automated access ..."), which used to
# trip the bot-marker check below.
#
# ISBN-13s starting with 978 map back to a unique ISBN-10. The newer 979
# prefix (post-2007) has no ISBN-10 form; for those we fall back to the
# ISBN-13 URL and accept that books in that narrow range may not resolve.

# Markers that indicate a real anti-bot interstitial (NOT the generic
# footer copy that appears on 404 pages). `validateCaptcha` is the form
# action on Amazon's actual captcha challenge; "Type the characters you
# see" is the captcha prompt; `<title>Robot Check</title>` is the dedicated
# challenge page title.
BOT_MARKERS: tuple[str, ...] = (
    "Type the characters you see",
    "<title>Robot Check</title>",
    "validateCaptcha",
)


class AmazonUKInlineSource(InlineSource):
    """Amazon UK scraper backed by headless Chromium (Playwright).

    Tries the dp page first; falls back to the offer-listing page if the dp
    page has no usable buy-box. See module docstring for protocol details.
    """

    def __init__(
        self,
        name: str = "amazon",
        region: str = "UK",
        timeout_s: float = 30.0,
    ) -> None:
        if region.upper() != "UK":
            raise ValueError(
                f"AmazonUKInlineSource only supports region='UK' at MVP, got {region!r}"
            )
        self.name = name
        self.region = region
        self.timeout_s = timeout_s

    def dp_url(self, isbn13: str) -> str:
        return amazon_uk_dp_url(isbn13)

    def offer_listing_url(self, isbn13: str) -> str:
        return f"https://www.amazon.co.uk/gp/offer-listing/{asin_for_amazon_uk(isbn13)}?condition=all"

    async def fetch(self, book: Book) -> list[ObservationCandidate]:
        dp = self.dp_url(book.isbn13)
        ol = self.offer_listing_url(book.isbn13)
        async with async_playwright() as pw:
            browser = await pw.chromium.launch(
                headless=True,
                args=["--no-sandbox", "--disable-blink-features=AutomationControlled"],
            )
            try:
                context = await browser.new_context(
                    viewport={"width": 1366, "height": 768},
                    locale="en-GB",
                )
                dp_html = await self._render_page(
                    context,
                    dp,
                    wait_selector=(
                        "#corePriceDisplay_desktop_feature_div, "
                        "#corePrice_feature_div, "
                        ".a-price .a-offscreen"
                    ),
                    # Buy-box renders fast; missing selector means no buy-box
                    # here, fall back rather than burn the full timeout.
                    wait_ms=min(10_000, int(self.timeout_s * 1000)),
                )
                offers = parse_dp(dp_html, dp)
                if offers:
                    return offers
                ol_html = await self._render_page(
                    context,
                    ol,
                    wait_selector="#aod-offer-list, .olpOfferList",
                    wait_ms=int(self.timeout_s * 1000),
                )
                return parse_offer_listing(ol_html, ol)
            finally:
                await browser.close()

    async def _render_page(
        self,
        context,
        url: str,
        *,
        wait_selector: str,
        wait_ms: int,
    ) -> str:
        """Open a page in `context`, navigate, return HTML after wait.

        Selector-timeout is fine — capture content and let the parser decide
        whether to fall back / report empty.
        """
        page = await context.new_page()
        try:
            await page.goto(
                url, wait_until="domcontentloaded", timeout=self.timeout_s * 1000
            )
        except PlaywrightTimeoutError as e:
            raise SourceError(self.name, f"navigation timed out: {e}") from e
        try:
            await page.wait_for_selector(wait_selector, timeout=wait_ms, state="attached")
        except PlaywrightTimeoutError:
            pass
        html = await page.content()
        for marker in BOT_MARKERS:
            if marker in html:
                raise SourceError(
                    self.name,
                    "Amazon bot-protection challenge persisted; "
                    "Playwright was unable to clear it",
                )
        return html


_FREE_DELIVERY_RE = re.compile(r"\bFREE\s+delivery\b", re.IGNORECASE)
# Matches "£2.80 delivery" / "£ 2.80 delivery"; intentionally not symmetric
# with "delivery £2.80" because no real Amazon UK dp markup uses that order
# (verified against live captures 2026-05-15). Add the reverse if we ever see it.
_PAID_DELIVERY_RE = re.compile(
    r"£\s*(\d+(?:\.\d{1,2})?)\s*delivery", re.IGNORECASE
)
# Containers Amazon UK uses to surface the buy-box delivery line. In order of
# preference: the static MIR slot (always populated when present), then the
# legacy deliveryBlockMessage, then the dynamic widget that A/B-tests render
# instead of MIR. We return on the first one that has actual text — empty
# nodes are skipped because Amazon ships skeleton markup it hydrates later.
_DELIVERY_BLOCK_SELECTORS: tuple[str, ...] = (
    "#mir-layout-DELIVERY_BLOCK-slot-PRIMARY_DELIVERY_MESSAGE_LARGE",
    "#deliveryBlockMessage",
    "#dynamicDeliveryMessage",
)


def _extract_dp_shipping_minor(tree: HTMLParser) -> int | None:
    """Pull the buy-box delivery cost in pence from `tree`, or None.

    Returns 0 when the delivery line says "FREE delivery", an integer pence
    value when it says "£X.XX delivery", and None when no populated delivery
    block is present — None means "we didn't observe shipping" rather than
    "free", so downstream can choose to fall back honestly.
    """
    for sel in _DELIVERY_BLOCK_SELECTORS:
        node = tree.css_first(sel)
        if node is None:
            continue
        text = (node.text() or "").strip()
        if not text:
            continue
        if _FREE_DELIVERY_RE.search(text):
            return 0
        m = _PAID_DELIVERY_RE.search(text)
        if m:
            try:
                return round(float(m.group(1)) * 100)
            except ValueError:
                continue
    return None


def parse_dp(html: str, fallback_url: str) -> list[ObservationCandidate]:
    """Parse Amazon UK dp-page HTML into ObservationCandidates.

    Returns at most one offer (the buy-box). Empty list means no usable
    price was found — the caller should fall back to the offer-listing page.

    Price extraction tries two paths in order:
      1. selectolax CSS scrape of `.a-price .a-offscreen` under the
         corePriceDisplay scope (cheap, works on simpler pages).
      2. Regex against `"priceAmount":<float>` in the raw HTML (slower
         but robust against Amazon's hydration shuffle that moves the
         visible buy-box element out of the corePriceDisplay subtree).
    """
    if not html:
        return []
    tree = HTMLParser(html)

    price_minor: int | None = None
    for sel in (
        "#corePriceDisplay_desktop_feature_div",
        "#corePrice_feature_div",
        "#priceblock_ourprice",
        "#price",
    ):
        scope = tree.css_first(sel)
        if scope is not None:
            price_minor = _extract_price_minor(scope)
            if price_minor is not None:
                break

    if price_minor is None:
        price_minor = _extract_priceamount_minor(html)
    if price_minor is None:
        return []

    seller = _extract_dp_seller(tree)
    shipping_minor = _extract_dp_shipping_minor(tree)

    return [
        ObservationCandidate(
            seller=seller,
            condition="new",  # Amazon dp buy-box defaults to new
            price_minor=price_minor,
            shipping_minor=shipping_minor,
            currency="GBP",
            url=fallback_url,
        )
    ]


def _extract_priceamount_minor(html: str) -> int | None:
    """Return the first `"priceAmount":<n>` value from `html` as pence, or None."""
    m = _PRICE_AMOUNT_RE.search(html)
    if m is None:
        return None
    try:
        return round(float(m.group(1)) * 100)
    except ValueError:
        return None


def parse_offer_listing(html: str, fallback_url: str) -> list[ObservationCandidate]:
    """Parse Amazon UK offer-listing-page HTML into ObservationCandidates."""
    if not html:
        return []
    tree = HTMLParser(html)

    # Modern AOD layout: #aod-offer rows under #aod-offer-list.
    # Legacy fallback: .olpOffer rows.
    rows = tree.css("#aod-offer-list #aod-offer")
    if not rows:
        rows = tree.css(".olpOffer")

    offers: list[ObservationCandidate] = []
    for row in rows:
        offer = _parse_offer_row(row, fallback_url)
        if offer is not None:
            offers.append(offer)
    return offers


def _parse_offer_row(row: Node, fallback_url: str) -> ObservationCandidate | None:
    price_minor = _extract_price_minor(row)
    if price_minor is None:
        return None

    shipping_minor = _extract_shipping_minor(row)
    condition = _extract_condition(row)
    seller = _extract_offer_seller(row)
    clickout = _extract_clickout(row, fallback_url)

    return ObservationCandidate(
        seller=seller,
        condition=condition,
        price_minor=price_minor,
        shipping_minor=shipping_minor,
        currency="GBP",
        url=clickout,
    )


def _extract_price_minor(scope: Node) -> int | None:
    """Pull the price in pence from a `.a-price .a-offscreen` node under `scope`.

    Amazon's price markup always pairs the visible `.a-price-whole/.a-price-fraction`
    spans with a screen-reader `.a-offscreen` carrying the full "£7.99" string;
    we read the latter.

    When a product is discounted, the dp page renders BOTH the current
    selling price (under `.a-price.apex-core-price-identifier` or a similar
    sibling) AND the strike-through RRP (under `.a-price.basisPrice`).
    Picking the first `.a-offscreen` in document order would silently use
    the RRP on every discounted listing. Skip any node whose ancestor
    chain includes `.basisPrice` (also catches `apb-price-was` and similar
    "was" markers used by Amazon's A/B variants).
    """
    for off in scope.css(".a-price .a-offscreen"):
        if _ancestor_has_class(off, ("basisPrice", "apb-price-was", "a-text-strike")):
            continue
        minor = _parse_gbp_to_minor((off.text() or "").strip())
        if minor is not None:
            return minor
    return None


def _ancestor_has_class(node: Node, class_tokens: tuple[str, ...]) -> bool:
    """True if any ancestor of `node` has one of the given class tokens."""
    cur = node.parent
    while cur is not None:
        attrs = cur.attributes or {}
        classes = (attrs.get("class") or "").split()
        if any(t in classes for t in class_tokens):
            return True
        cur = cur.parent
    return False


def _parse_gbp_to_minor(text: str) -> int | None:
    """Parse "£7.99" / "&pound;7.99" / "7.99" → 799 (pence)."""
    if not text:
        return None
    m = _PRICE_NUMERIC_RE.search(text)
    if m is None:
        return None
    try:
        return round(float(m.group(1)) * 100)
    except ValueError:
        return None


def _extract_shipping_minor(row: Node) -> int | None:
    """Extract shipping cost in pence from an offer row; 0 for FREE."""
    ship_node = row.css_first("#aod-offer-shipping")
    if ship_node is None:
        return None
    text = (ship_node.text() or "").strip()
    if not text:
        return None
    if "free" in text.lower():
        return 0
    return _parse_gbp_to_minor(text)


def _extract_condition(row: Node) -> Condition:
    """Map the row's heading text ("Used - Very Good" etc.) to our enum."""
    heading = row.css_first("#aod-offer-heading h5") or row.css_first("#aod-offer-heading")
    return condition_from_grade_text(heading.text() or "") if heading else "unknown"


def _extract_offer_seller(row: Node) -> str:
    node = row.css_first("#aod-offer-soldBy a") or row.css_first("#aod-offer-soldBy")
    return _node_text(node) or "?"


def _extract_clickout(row: Node, fallback_url: str) -> str:
    for anchor in row.css("a[href]"):
        href = anchor.attributes.get("href") or ""
        if href.startswith("http"):
            return href
        if href.startswith("/"):
            return "https://www.amazon.co.uk" + href
    return fallback_url


def _extract_dp_seller(tree: HTMLParser) -> str:
    return (
        _node_text(tree.css_first("#merchant-info a"))
        or _node_text(tree.css_first("#merchant-info"))
        or "Amazon"
    )


def _node_text(node: Node | None) -> str:
    """Stripped inner text from a node, or '' if the node is None / empty."""
    return (node.text() or "").strip() if node is not None else ""
