from __future__ import annotations

import re

from playwright.async_api import (
    TimeoutError as PlaywrightTimeoutError,
)
from playwright.async_api import (
    async_playwright,
)
from selectolax.parser import HTMLParser, Node

from book_alerter.db.models import Book, Condition, Product
from book_alerter.enums import ItemKind
from book_alerter.sources.base import (
    ObservationCandidate,
    SourceError,
    TrackedItem,
)
from book_alerter.sources.condition_normalizers import condition_from_grade_text
from book_alerter.sources.inline_source import InlineSource
from book_alerter.sources.normalizers import (
    amazon_uk_dp_url,
    amazon_uk_product_dp_url,
    asin_for_amazon_uk,
)

# Amazon UK is fronted by aggressive bot-protection that defeats any client
# that doesn't render JS in a real browser (verified 2026-05-14: headless
# Chromium + stealth flags + cookie warm-up still got served the
# "To discuss automated access to Amazon" interstitial). So this source
# drives headless Chromium via Playwright for every lookup.
#
# Strategy: render BOTH /dp/<ISBN> and /gp/offer-listing/<ISBN>?condition=all
# on every fetch and merge. The dp buy-box almost always also appears as a
# row on the offer-listing page, so a merge-with-dedup gives us the union:
# the new buy-box guaranteed (even on books with a marketplace-empty AOD
# page) plus every used grade Amazon publishes on the marketplace.
#
# Region: UK only at MVP. Pass region="UK" or accept the default.
#
# DOM contract:
#   dp page          - buy-box price under #corePriceDisplay_desktop_feature_div
#                      OR #corePrice_feature_div. Within, .a-price wraps the
#                      number; .a-offscreen carries the screen-reader-friendly
#                      full price ("£7.99"). Prefer .a-offscreen — it's the
#                      most stable selector.
#   offer-listing    - rows under #aod-offer-list, each `#aod-offer` (modern
#                      AOD layout). Legacy fallback: `.olpOffer`. Within each
#                      row: #aod-offer-price (.a-offscreen), #aod-offer-shipping,
#                      #aod-offer-heading (h5 text with the condition),
#                      #aod-offer-soldBy (seller link text).

# Tolerates "£7.99" / "&pound;7.99" / "7.99" — whichever DOM branch we end
# up reading.
_PRICE_NUMERIC_RE = re.compile(r"(\d+(?:\.\d{1,2})?)")

# Fallback path for the dp buy-box price. Amazon's inline JS state embeds
# the current selling price as `"priceAmount":34.52` somewhere in the
# HTML body, ahead of any "lowest used/new from £X" sub-prices. selectolax
# CSS scraping of `.a-price .a-offscreen` is unreliable on this page —
# Amazon's React hydration moves the actual buy-box element around between
# initial render and post-hydration, so the static HTML selectolax sees
# doesn't always contain the visible buy-box price under the expected
# corePriceDisplay scope. The priceAmount field is generated by Amazon's
# pricing service and reflects the same number rendered to the user.
_PRICE_AMOUNT_RE = re.compile(r'"priceAmount"\s*:\s*(\d+(?:\.\d{1,2})?)')

# Amazon UK indexes books by ISBN-10 (which IS the ASIN for books). The /dp
# and /gp/offer-listing URLs only resolve to a real product page when the path
# segment is the ISBN-10. /dp/{ISBN-13} silently serves a generic ~2 KB "Page
# Not Found" instead of redirecting — the page still contains Amazon's
# standard footer copy ("To discuss automated access ..."), which used to
# trip the bot-marker check below.
#
# ISBN-13s starting with 978 map back to a unique ISBN-10. The newer 979
# prefix (post-2007) has no ISBN-10 form; for those we fall back to the
# ISBN-13 URL and accept that books in that narrow range may not resolve.

# Markers that indicate a real anti-bot interstitial (NOT the generic
# footer copy that appears on 404 pages). `validateCaptcha` is the form
# action on Amazon's actual captcha challenge; "Type the characters you
# see" is the captcha prompt; `<title>Robot Check</title>` is the dedicated
# challenge page title.
BOT_MARKERS: tuple[str, ...] = (
    "Type the characters you see",
    "<title>Robot Check</title>",
    "validateCaptcha",
)

# Positive selectors that confirm we're actually looking at the expected
# Amazon UK page layout. Used by the parsers to distinguish "we parsed the
# page and there really are no offers" from "Amazon served something we
# don't recognise" — the latter must raise rather than silently report 0,
# otherwise a new anti-bot variant (one whose substring isn't in BOT_MARKERS)
# would look like a successful empty fetch.
#
# `#dp-container` and `#productTitle` together cover every dp-page variant
# we've captured: the real-capture fixture, the synthetic dp/no-price
# variant (productTitle present), and the synthetic delivery-block fixtures
# (productTitle stripped, dp-container retained).
_DP_PAGE_MARKERS: tuple[str, ...] = ("#dp-container", "#productTitle")
# AOD is the modern offer-listing layout; OLP is the legacy fallback. Both
# fixtures + real captures use the `aod-container` / `aod-offer-list` IDs.
_OFFER_LISTING_PAGE_MARKERS: tuple[str, ...] = (
    "#aod-container",
    "#aod-offer-list",
    "#olpOfferList",
    "#olpProductInformation",
)


def _matches_any_selector(tree: HTMLParser, selectors: tuple[str, ...]) -> bool:
    return any(tree.css_first(sel) is not None for sel in selectors)


class AmazonUKInlineSource(InlineSource):
    """Amazon UK scraper backed by headless Chromium (Playwright).

    Renders both the dp and the offer-listing pages on every fetch and
    merges the offers, deduping rows that appear on both. Books-only —
    `AmazonUKProductInlineSource` handles products. Both share the lower-
    level `_fetch_offers_for_asin` helper so DOM contract changes only need
    to land in one place.
    """

    def __init__(
        self,
        name: str = "amazon",
        region: str = "UK",
        timeout_s: float = 30.0,
    ) -> None:
        if region.upper() != "UK":
            raise ValueError(
                f"AmazonUKInlineSource only supports region='UK' at MVP, got {region!r}"
            )
        self.name = name
        self.region = region
        self.timeout_s = timeout_s

    def dp_url(self, isbn13: str) -> str:
        return amazon_uk_dp_url(isbn13)

    def offer_listing_url(self, isbn13: str) -> str:
        return _offer_listing_url_for_asin(asin_for_amazon_uk(isbn13))

    async def fetch(self, item: TrackedItem) -> list[ObservationCandidate]:
        # Books-only source. Defence in depth: scheduler already filters by
        # item_kinds, but a misconfigured Source instance is the kind of
        # thing we'd rather hit hard than silently no-op.
        assert isinstance(item, Book), f"{self.name} only handles books"
        # Books always track every condition Amazon publishes — the used
        # market is the whole point of the book pipeline.
        return await _fetch_offers_for_asin(
            asin_for_amazon_uk(item.isbn13),
            source_name=self.name,
            timeout_s=self.timeout_s,
            track_used=True,
        )

    async def _render_page(
        self,
        context,
        url: str,
        *,
        wait_selector: str,
        wait_ms: int,
    ) -> str:
        """Open a page in `context`, navigate, return HTML after wait.

        Kept as an instance method only because two tests poke it
        directly; the AmazonProductSource uses the module-level
        `_render_amazon_page` helper. Both call sites share the same
        Playwright logic; do not let the two implementations drift.
        """
        return await _render_amazon_page(
            context,
            url,
            wait_selector=wait_selector,
            wait_ms=wait_ms,
            navigation_timeout_s=self.timeout_s,
            source_name=self.name,
        )


def _offer_listing_url_for_asin(asin: str) -> str:
    return f"https://www.amazon.co.uk/gp/offer-listing/{asin}?condition=all"


async def _render_amazon_page(
    context,
    url: str,
    *,
    wait_selector: str,
    wait_ms: int,
    navigation_timeout_s: float,
    source_name: str,
) -> str:
    """Open `url` in a Playwright `context`, wait for `wait_selector`, return
    rendered HTML. Selector-timeout is fine — capture content and let the
    parser decide whether to fall back or report empty. Raises SourceError
    on navigation timeout or persistent bot-challenge marker.
    """
    page = await context.new_page()
    try:
        await page.goto(
            url, wait_until="domcontentloaded", timeout=navigation_timeout_s * 1000
        )
    except PlaywrightTimeoutError as e:
        raise SourceError(source_name, f"navigation timed out: {e}") from e
    try:
        await page.wait_for_selector(wait_selector, timeout=wait_ms, state="attached")
    except PlaywrightTimeoutError:
        pass
    html = await page.content()
    for marker in BOT_MARKERS:
        if marker in html:
            raise SourceError(
                source_name,
                "Amazon bot-protection challenge persisted; "
                "Playwright was unable to clear it",
            )
    return html


async def _fetch_offers_for_asin(
    asin: str,
    *,
    source_name: str,
    timeout_s: float,
    track_used: bool,
) -> list[ObservationCandidate]:
    """Render Amazon UK dp + offer-listing for `asin`, merge + dedup.

    `track_used=False` filters out non-NEW conditions before merging — used
    by `AmazonUKProductInlineSource` because most non-book products have no
    meaningful used market on Amazon. Books always pass `True`.

    Shared between the book source and the product source so the Playwright
    dance, bot-marker handling, and DOM contract live in one place.
    """
    dp_url = f"https://www.amazon.co.uk/dp/{asin}"
    offer_url = _offer_listing_url_for_asin(asin)
    async with async_playwright() as pw:
        browser = await pw.chromium.launch(
            headless=True,
            args=["--no-sandbox", "--disable-blink-features=AutomationControlled"],
        )
        try:
            context = await browser.new_context(
                viewport={"width": 1366, "height": 768},
                locale="en-GB",
            )
            dp_html = await _render_amazon_page(
                context,
                dp_url,
                wait_selector=(
                    "#corePriceDisplay_desktop_feature_div, "
                    "#corePrice_feature_div, "
                    ".a-price .a-offscreen"
                ),
                # Buy-box renders fast — cap the wait so a buy-box-less
                # listing doesn't burn the full Playwright timeout.
                wait_ms=min(10_000, int(timeout_s * 1000)),
                navigation_timeout_s=timeout_s,
                source_name=source_name,
            )
            dp_offers = parse_dp(dp_html, dp_url, source_name=source_name)
            offer_html = await _render_amazon_page(
                context,
                offer_url,
                wait_selector="#aod-offer-list, .olpOfferList",
                wait_ms=int(timeout_s * 1000),
                navigation_timeout_s=timeout_s,
                source_name=source_name,
            )
            offer_listing_offers = parse_offer_listing(
                offer_html, offer_url, source_name=source_name,
            )
            merged = _merge_offers([*dp_offers, *offer_listing_offers])
            if not track_used:
                merged = [o for o in merged if o.condition == Condition.NEW]
            return merged
        finally:
            await browser.close()


class AmazonUKProductInlineSource(InlineSource):
    """Amazon UK scraper for non-book products. ASIN comes straight from
    `Product.asin` (no ISBN conversion). Honours `Product.track_used` for
    the per-row used-market opt-in.
    """

    name = "amazon_uk_product"
    item_kinds = frozenset({ItemKind.PRODUCT})

    def __init__(
        self,
        name: str = "amazon_uk_product",
        region: str = "UK",
        timeout_s: float = 30.0,
    ) -> None:
        if region.upper() != "UK":
            raise ValueError(
                f"AmazonUKProductInlineSource only supports region='UK' at MVP, got {region!r}"
            )
        self.name = name
        self.region = region
        self.timeout_s = timeout_s

    def dp_url(self, asin: str) -> str:
        return amazon_uk_product_dp_url(asin)

    def offer_listing_url(self, asin: str) -> str:
        return _offer_listing_url_for_asin(asin)

    async def fetch(self, item: TrackedItem) -> list[ObservationCandidate]:
        assert isinstance(item, Product), f"{self.name} only handles products"
        return await _fetch_offers_for_asin(
            item.asin,
            source_name=self.name,
            timeout_s=self.timeout_s,
            track_used=item.track_used,
        )


def _normalize_seller(seller: str | None) -> str:
    """Case- and whitespace-insensitive seller key.

    Uses `.lower()` (not `.casefold()`) to stay in lockstep with SQLite's
    ASCII-only `LOWER()` used by the persistence-layer match in
    `scheduler._persist`. For Amazon UK seller names (all ASCII in
    practice) lower() == casefold(), so the choice only matters when
    paranoid Unicode parity comes up — and SQLite's LOWER is the
    constraint that pins the choice.
    """
    return (seller or "").strip().lower()


def _merge_offers(offers: list[ObservationCandidate]) -> list[ObservationCandidate]:
    """Merge dp + offer-listing offers, deduping rows that describe the same offer.

    Match on (normalized seller, condition, price_minor). Shipping is left
    out of the key because the dp delivery block and the offer-listing
    `#aod-offer-shipping` line can disagree representationally for the
    same buy-box offer (the dp slot may be hydration-skeletoned to
    shipping_minor=None while the offer-listing row resolves to 0 from
    "FREE delivery"). When a duplicate is found, the entry with concrete
    shipping data wins over one with shipping_minor=None — a known value
    beats no information.
    """
    by_key: dict[tuple[str, str, int], ObservationCandidate] = {}
    for o in offers:
        key = (_normalize_seller(o.seller), o.condition, o.price_minor)
        existing = by_key.get(key)
        if existing is None:
            by_key[key] = o
            continue
        if existing.shipping_minor is None and o.shipping_minor is not None:
            by_key[key] = o
    return list(by_key.values())


_FREE_DELIVERY_RE = re.compile(r"\bFREE\s+delivery\b", re.IGNORECASE)
# Matches "£2.80 delivery" / "£ 2.80 delivery"; intentionally not symmetric
# with "delivery £2.80" because no real Amazon UK dp markup uses that order
# (verified against live captures 2026-05-15). Add the reverse if we ever see it.
_PAID_DELIVERY_RE = re.compile(
    r"£\s*(\d+(?:\.\d{1,2})?)\s*delivery", re.IGNORECASE
)
# Containers Amazon UK uses to surface the buy-box delivery line. In order of
# preference: the static MIR slot (always populated when present), then the
# legacy deliveryBlockMessage, then the dynamic widget that A/B-tests render
# instead of MIR. We return on the first one that has actual text — empty
# nodes are skipped because Amazon ships skeleton markup it hydrates later.
_DELIVERY_BLOCK_SELECTORS: tuple[str, ...] = (
    "#mir-layout-DELIVERY_BLOCK-slot-PRIMARY_DELIVERY_MESSAGE_LARGE",
    "#deliveryBlockMessage",
    "#dynamicDeliveryMessage",
)


def _extract_dp_shipping_minor(tree: HTMLParser) -> int | None:
    """Pull the buy-box delivery cost in pence from `tree`, or None.

    Returns 0 when the delivery line says "FREE delivery", an integer pence
    value when it says "£X.XX delivery", and None when no populated delivery
    block is present — None means "we didn't observe shipping" rather than
    "free", so downstream can choose to fall back honestly.
    """
    for sel in _DELIVERY_BLOCK_SELECTORS:
        node = tree.css_first(sel)
        if node is None:
            continue
        text = (node.text() or "").strip()
        if not text:
            continue
        if _FREE_DELIVERY_RE.search(text):
            return 0
        m = _PAID_DELIVERY_RE.search(text)
        if m:
            try:
                return round(float(m.group(1)) * 100)
            except ValueError:
                continue
    return None


def parse_dp(
    html: str,
    fallback_url: str,
    *,
    source_name: str = "amazon",
) -> list[ObservationCandidate]:
    """Parse Amazon UK dp-page HTML into ObservationCandidates.

    Returns at most one offer (the buy-box). Empty list means no usable
    price was found — the caller should fall back to the offer-listing page.

    `source_name` is used in the SourceError message only — both book and
    product sources call this helper; default `"amazon"` keeps existing
    tests that don't pass the kwarg passing.

    Price extraction tries two paths in order:
      1. selectolax CSS scrape of `.a-price .a-offscreen` under the
         corePriceDisplay scope (cheap, works on simpler pages).
      2. Regex against `"priceAmount":<float>` in the raw HTML (slower
         but robust against Amazon's hydration shuffle that moves the
         visible buy-box element out of the corePriceDisplay subtree).
    """
    if not html:
        return []
    tree = HTMLParser(html)

    price_minor: int | None = None
    for sel in (
        "#corePriceDisplay_desktop_feature_div",
        "#corePrice_feature_div",
        "#priceblock_ourprice",
        "#price",
    ):
        scope = tree.css_first(sel)
        if scope is not None:
            price_minor = _extract_price_minor(scope)
            if price_minor is not None:
                break

    if price_minor is None:
        price_minor = _extract_priceamount_minor(tree, html)
    if price_minor is None:
        # No buy-box price found. Distinguish "real Amazon dp page with no
        # buy-box / unavailable" (return []) from "Amazon served something
        # we don't recognise" (raise) — see `_DP_PAGE_MARKERS` rationale.
        if not _matches_any_selector(tree, _DP_PAGE_MARKERS):
            raise SourceError(
                source_name,
                "dp page did not match any known Amazon UK layout "
                "(no buy-box price, no #dp-container or #productTitle); "
                "treating as anti-bot variant rather than reporting 0 offers",
            )
        return []

    seller = _extract_dp_seller(tree)
    shipping_minor = _extract_dp_shipping_minor(tree)

    return [
        ObservationCandidate(
            seller=seller,
            condition=Condition.NEW,  # Amazon dp buy-box defaults to new
            price_minor=price_minor,
            shipping_minor=shipping_minor,
            currency="GBP",
            url=fallback_url,
        )
    ]


def _extract_priceamount_minor(tree: HTMLParser, html: str) -> int | None:
    """Return the buy-box `priceAmount` in pence, or None.

    Scoping rationale: Amazon's pricing service serializes the buy-box
    price into a `twister-plus-buying-options-price-data` div as JSON
    keyed by `desktop_buybox_group_<N>`. Searching the FULL page HTML
    with the priceAmount regex used to work by happy accident — the
    buy-box JSON happened to appear before any other `"priceAmount"`
    occurrence on every captured page. But Amazon also embeds priceAmount
    in unrelated rails (frequently-bought-together, recommended titles,
    seller-storefront cards) and there's no guarantee the buy-box block
    stays first when Amazon reshuffles the DOM. Scope to the buy-box
    data div when present so the regex can't drift onto an unrelated
    price. If the div isn't found (older layout, A/B variant), fall
    back to the page-wide search rather than silently dropping the
    fallback price path entirely.
    """
    scope = tree.css_first("div.twister-plus-buying-options-price-data")
    haystack = scope.text() if scope is not None else html
    m = _PRICE_AMOUNT_RE.search(haystack)
    if m is None:
        return None
    try:
        return round(float(m.group(1)) * 100)
    except ValueError:
        return None


def parse_offer_listing(
    html: str,
    fallback_url: str,
    *,
    source_name: str = "amazon",
) -> list[ObservationCandidate]:
    """Parse Amazon UK offer-listing-page HTML into ObservationCandidates.

    `source_name` is used in the SourceError message only — both book and
    product sources call this helper; default `"amazon"` keeps existing
    tests that don't pass the kwarg passing.
    """
    if not html:
        return []
    tree = HTMLParser(html)

    # Modern AOD layout: #aod-offer rows under #aod-offer-list.
    # Legacy fallback: .olpOffer rows.
    rows = tree.css("#aod-offer-list #aod-offer")
    if not rows:
        rows = tree.css(".olpOffer")

    offers: list[ObservationCandidate] = []
    for row in rows:
        offer = _parse_offer_row(row, fallback_url)
        if offer is not None:
            offers.append(offer)
    if not offers and not _matches_any_selector(tree, _OFFER_LISTING_PAGE_MARKERS):
        # No rows found AND no recognised offer-listing container — Amazon
        # almost certainly served an anti-bot or unrelated variant. Raise
        # rather than report 0; see `_OFFER_LISTING_PAGE_MARKERS` rationale.
        raise SourceError(
            source_name,
            "offer-listing page did not match any known Amazon UK layout "
            "(no #aod-container / #aod-offer-list / #olpOfferList); "
            "treating as anti-bot variant rather than reporting 0 offers",
        )
    return offers


def _parse_offer_row(row: Node, fallback_url: str) -> ObservationCandidate | None:
    price_minor = _extract_price_minor(row)
    if price_minor is None:
        return None

    shipping_minor = _extract_shipping_minor(row)
    condition = _extract_condition(row)
    seller = _extract_offer_seller(row)
    clickout = _extract_clickout(row, fallback_url)

    return ObservationCandidate(
        seller=seller,
        condition=condition,
        price_minor=price_minor,
        shipping_minor=shipping_minor,
        currency="GBP",
        url=clickout,
    )


# Class tokens that mark a price span as a strike-through RRP rather than
# the actual offer price. `basisPrice` is the legacy hook; the modern apex
# pricing template uses `apex-basisprice-value` for the inner `<span>` and
# `centralizedApexBasisPriceCSS` for its container. `apb-price-was` and
# `a-text-strike` cover older A/B variants.
_STRIKE_THROUGH_ANCESTORS: tuple[str, ...] = (
    "basisPrice",
    "apex-basisprice-value",
    "centralizedApexBasisPriceCSS",
    "apb-price-was",
    "a-text-strike",
)


def _extract_price_minor(scope: Node) -> int | None:
    """Pull the offer price in pence from `scope`.

    Two paths, tried in order:

    1. `.apex-pricetopay-accessibility-label` — modern apex pricing
       template renders the offer price as plain text inside an
       `aok-offscreen` span carrying this class. It sits as a SIBLING of
       `.a-price` (not a child), so the legacy `.a-price .a-offscreen`
       scan below cannot reach it. Real Amazon UK offer-listing rows ship
       the `.a-offscreen` inside `.a-price` empty for the offer price —
       the visible price is assembled from `.a-price-whole` /
       `.a-price-fraction` under `aria-hidden=true` — which is why a
       parser that only walks `.a-price .a-offscreen` ends up picking up
       the strike-through RRP instead. Reading the pricetopay
       accessibility label fixes this.

    2. Fallback: `.a-price .a-offscreen` scan, used by the synthetic
       fixtures and older AOD templates. Skip strike-through RRPs via
       `_STRIKE_THROUGH_ANCESTORS`.
    """
    for label in scope.css(".apex-pricetopay-accessibility-label"):
        if _ancestor_has_class(label, _STRIKE_THROUGH_ANCESTORS):
            continue
        minor = _parse_gbp_to_minor((label.text() or "").strip())
        if minor is not None:
            return minor
    for off in scope.css(".a-price .a-offscreen"):
        if _ancestor_has_class(off, _STRIKE_THROUGH_ANCESTORS):
            continue
        minor = _parse_gbp_to_minor((off.text() or "").strip())
        if minor is not None:
            return minor
    return None


def _ancestor_has_class(node: Node, class_tokens: tuple[str, ...]) -> bool:
    """True if any ancestor of `node` has one of the given class tokens."""
    cur = node.parent
    while cur is not None:
        attrs = cur.attributes or {}
        classes = (attrs.get("class") or "").split()
        if any(t in classes for t in class_tokens):
            return True
        cur = cur.parent
    return False


def _parse_gbp_to_minor(text: str) -> int | None:
    """Parse "£7.99" / "&pound;7.99" / "7.99" → 799 (pence)."""
    if not text:
        return None
    m = _PRICE_NUMERIC_RE.search(text)
    if m is None:
        return None
    try:
        return round(float(m.group(1)) * 100)
    except ValueError:
        return None


def _extract_shipping_minor(row: Node) -> int | None:
    """Extract shipping cost in pence from an offer row; 0 for FREE."""
    ship_node = row.css_first("#aod-offer-shipping")
    if ship_node is None:
        return None
    text = (ship_node.text() or "").strip()
    if not text:
        return None
    if "free" in text.lower():
        return 0
    return _parse_gbp_to_minor(text)


def _extract_condition(row: Node) -> Condition:
    """Map the row's heading text ("Used - Very Good" etc.) to our enum."""
    heading = row.css_first("#aod-offer-heading h5") or row.css_first("#aod-offer-heading")
    return condition_from_grade_text(heading.text() or "") if heading else "unknown"


_ARIA_LABEL_SELLER_SUFFIX = ". Opens a new page"


def _extract_offer_seller(row: Node) -> str:
    """Read the seller name from an offer-listing row.

    Real Amazon UK markup uses two layouts in the soldBy block:

      - Marketplace seller: `<a aria-label="SellerName. Opens a new page"
        ...>SellerName </a>` plus a sibling `<div id="aod-offer-seller-rating">`
        carrying a rating tooltip ("Seller rating is 5 out of 5 stars").
      - Amazon-direct: no `<a>` — just `<span aria-label="Amazon. Opens a
        new page">Amazon</span>` next to the "Sold by" label span.

    Both cases attach the seller's name to an `aria-label` ending in
    "Opens a new page". Reading that attribute is the most reliable way
    to get just the seller's name without leaking the "Sold by" prefix
    or the seller-rating tooltip into the result. The element-text and
    div-text fallbacks remain for older markup variants and the
    synthetic fixtures.
    """
    for el in row.css("#aod-offer-soldBy [aria-label]"):
        label = (el.attributes.get("aria-label") or "").strip()
        if not label:
            continue
        cleaned = label.removesuffix(_ARIA_LABEL_SELLER_SUFFIX).strip()
        if cleaned:
            return cleaned
    a_text = _node_text(row.css_first("#aod-offer-soldBy a"))
    if a_text:
        return a_text
    div = row.css_first("#aod-offer-soldBy")
    if div is None:
        return "?"
    text = " ".join((div.text() or "").split()).strip()
    for prefix in ("Sold by:", "Sold by"):
        cleaned = text.removeprefix(prefix).strip(" : ")
        if cleaned != text:
            text = cleaned
            break
    return text or "?"


def _extract_clickout(row: Node, fallback_url: str) -> str:
    for anchor in row.css("a[href]"):
        href = anchor.attributes.get("href") or ""
        if href.startswith("http"):
            return href
        if href.startswith("/"):
            return "https://www.amazon.co.uk" + href
    return fallback_url


def _extract_dp_seller(tree: HTMLParser) -> str:
    return (
        _node_text(tree.css_first("#merchant-info a"))
        or _node_text(tree.css_first("#merchant-info"))
        or "Amazon"
    )


def _node_text(node: Node | None) -> str:
    """Stripped inner text from a node, or '' if the node is None / empty."""
    return (node.text() or "").strip() if node is not None else ""
