/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Books */
        get: operations["list_books_api_books_get"];
        put?: never;
        /** Create Book */
        post: operations["create_book_api_books_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{book_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Book */
        get: operations["get_book_api_books__book_id__get"];
        put?: never;
        post?: never;
        /** Delete Book */
        delete: operations["delete_book_api_books__book_id__delete"];
        options?: never;
        head?: never;
        /** Patch Book */
        patch: operations["patch_book_api_books__book_id__patch"];
        trace?: never;
    };
    "/api/books/{book_id}/observations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Observations
         * @description Paginated price history for a book (newest-first).
         *
         *     Excludes deduplicated rows (`is_duplicate_of IS NOT NULL`). Cursor via
         *     `before` (ISO 8601 `observed_at`); response includes `next_before` for the
         *     next page.
         */
        get: operations["list_observations_api_books__book_id__observations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{book_id}/refetch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refetch Book
         * @description Trigger an immediate scrape across every enabled source for this book.
         *
         *     The refetch button is "ask all sources about this book again" — it does
         *     **not** pre-filter by which sources have observed the book. Disabled
         *     sources surface in `skipped` with `reason="disabled"`; sources whose
         *     backoff gate is active (scheduler returns 0) surface with
         *     `reason="backoff_active"`. 404 if the book id is not found.
         */
        post: operations["refetch_book_api_books__book_id__refetch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{book_id}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Book Stats
         * @description Return the full `BookStats` for a book (zero-obs case included).
         */
        get: operations["get_book_stats_api_books__book_id__stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{book_id}/keepa-backfill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Keepa Backfill
         * @description Trigger a one-shot Keepa backfill. Idempotent.
         *
         *     Returns inserted=0 if a previous backfill already populated this book.
         *     Synchronous (awaits the extraction) so the caller gets a real count;
         *     the book-creation auto-backfill is fire-and-forget via BackgroundTasks.
         */
        post: operations["keepa_backfill_api_books__book_id__keepa_backfill_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{book_id}/keepa-chart.png": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Keepa Chart
         * @description Proxy the Keepa price-history PNG with a 24h server-side cache.
         *
         *     Hides the user's IP from Keepa and absorbs repeated FE loads.
         */
        get: operations["get_keepa_chart_api_books__book_id__keepa_chart_png_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Alerts
         * @description Cursor-paginated alerts feed (newest-first).
         *
         *     - `kind` filters by alert kind.
         *     - `dismissed=false` → only undismissed; `dismissed=true` → only dismissed;
         *       omitted → both.
         *     - `before` (ISO 8601 `fired_at`) is strict `<`; pass the previous page's
         *       `next_before` to fetch the next page.
         */
        get: operations["list_alerts_api_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts/{alert_id}/dismiss": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dismiss Alert
         * @description Dismiss an alert. Idempotent: re-dismissing preserves the original
         *     `dismissed_at` and still returns 200.
         */
        post: operations["dismiss_alert_api_alerts__alert_id__dismiss_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts/dismiss-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dismiss All Alerts
         * @description Bulk-dismiss every alert with `dismissed_at IS NULL`.
         *
         *     Single UPDATE — never iterates row-by-row. Returns the number of rows
         *     updated; previously-dismissed alerts retain their original timestamp.
         */
        post: operations["dismiss_all_alerts_api_alerts_dismiss_all_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sources
         * @description Per-source status, sorted alphabetically by source name.
         */
        get: operations["list_sources_api_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources/{name}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Source Runs
         * @description Recent `SourceRun` rows for `name`, newest first (default 10, max 100).
         *
         *     404 if `name` is not configured. Matches the wire shape of `last_run` in
         *     `GET /api/sources` (excludes `error_traceback`).
         */
        get: operations["list_source_runs_api_sources__name__runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources/{name}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Source Run
         * @description Trigger an immediate scrape via `scheduler.trigger_now(name)`.
         *
         *     Returns the new `SourceRun.id`. 404 if `name` is not in the configured
         *     sources. 409 when the scheduler returns 0 (backoff gate is active).
         */
        post: operations["trigger_source_run_api_sources__name__run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Source
         * @description Partial update of a source's config.
         *
         *     Only `enabled`, `schedule`, and `concurrency` may be patched (mirrors
         *     `SourcePatch`). Empty body is a 200 no-op. The whole config is re-validated
         *     via `Config.model_validate`, written back to disk via `Config.save`, and
         *     swapped into `app.state.config`.
         */
        patch: operations["patch_source_api_sources__name__patch"];
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Config
         * @description Return the current config as JSON.
         */
        get: operations["get_config_api_config_get"];
        /**
         * Put Config
         * @description Validate + (optionally) persist a new config.
         *
         *     Validation runs in both dry-run and apply modes; failures always return
         *     422. On apply, the existing config YAML is rotated to `<path>.bak` via
         *     `shutil.copy2` (preserves mtime) before the atomic write — single rotating
         *     backup, overwriting any prior `.bak`. No backup is created when the
         *     config file doesn't yet exist (first-write case).
         */
        put: operations["put_config_api_config_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Config Schema
         * @description Return the JSON Schema for the `Config` model.
         *
         *     Consumer: the future Monaco editor (Phase 11.5) uses this for live
         *     validation. Pydantic generates the schema; we don't massage it.
         */
        get: operations["get_config_schema_api_config_schema_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metadata/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Metadata Lookup
         * @description Normalize the input ISBN and race providers for metadata.
         *
         *     Returns 422 when the input can't be parsed as an ISBN, 404 when every
         *     provider (including the optional Amazon UK fallback) comes up empty.
         */
        get: operations["get_metadata_lookup_api_metadata_lookup_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metadata/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Metadata Search
         * @description Free-text search via Google Books. Empty list when no matches OR when
         *     Google returns 429/5xx (the FE handles empty as "no results"; surfacing
         *     the underlying error would just be misleading noise).
         */
        get: operations["get_metadata_search_api_metadata_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/{channel}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test Notification
         * @description Send a synthetic test alert through the named notifier channel.
         *
         *     The alert is constructed in memory and is **not persisted**. 404 if no
         *     notifier with that name is configured. The notifier's `NotificationResult`
         *     (`sent` or `error` with optional `error_message`) is surfaced verbatim so
         *     the UI can show the actual failure mode (e.g. "ntfy returned 401").
         */
        post: operations["test_notification_api_notifications__channel__test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AlertOut
         * @description Wire mirror of `book_alerter.db.models.Alert`.
         */
        AlertOut: {
            /** Id */
            id: number;
            /** Book Id */
            book_id: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "new_low" | "target_hit" | "percentile_cross";
            /** Price Minor */
            price_minor: number;
            /** Currency */
            currency: string;
            /** Source */
            source: string;
            /** Condition */
            condition: string;
            /** Message */
            message: string;
            /**
             * Fired At
             * Format: date-time
             */
            fired_at: string;
            /** Dismissed At */
            dismissed_at: string | null;
            /** Delivered Via */
            delivered_via: string[];
        };
        /**
         * AlertsPage
         * @description Cursor-paginated page of alerts (newest-first by `fired_at`).
         *
         *     `next_before` is the `fired_at` (ISO 8601) of the last row in `items`;
         *     pass it as `before` to fetch the next page. `None` when `len(items) <
         *     limit` (page not full → no more rows).
         */
        AlertsPage: {
            /** Items */
            items: components["schemas"]["AlertOut"][];
            /** Next Before */
            next_before: string | null;
        };
        /** BookCreate */
        BookCreate: {
            /** Isbn */
            isbn: string;
            /** Title */
            title: string;
            /** Author */
            author: string;
            /** Cover Url */
            cover_url?: string | null;
            /**
             * Format
             * @default any
             * @enum {string}
             */
            format: "paperback" | "hardcover" | "any";
            /** Target Price Minor */
            target_price_minor?: number | null;
            /** Percentile Threshold */
            percentile_threshold?: number | null;
            /** Percentile Window Days */
            percentile_window_days?: number | null;
            /** Notes */
            notes?: string | null;
        };
        /** BookMetadata */
        BookMetadata: {
            /** Title */
            title: string;
            /** Author */
            author: string;
            /** Cover Url */
            cover_url?: string | null;
        };
        /**
         * BookMetadataWithIsbn
         * @description A search-result row that carries its own ISBN-13 — distinct from
         *     `BookMetadata` (used by `/api/metadata/lookup` where the caller already
         *     has the ISBN). The add-book UI uses this shape to render
         *     "click to add" candidates.
         */
        BookMetadataWithIsbn: {
            /** Isbn13 */
            isbn13: string;
            /** Title */
            title: string;
            /** Author */
            author: string;
            /** Cover Url */
            cover_url?: string | null;
        };
        /** BookOut */
        BookOut: {
            /** Id */
            id: number;
            /** Isbn13 */
            isbn13: string;
            /** Title */
            title: string;
            /** Author */
            author: string;
            /** Cover Url */
            cover_url: string | null;
            /**
             * Format
             * @enum {string}
             */
            format: "paperback" | "hardcover" | "any";
            /** Region */
            region: string;
            /** Currency */
            currency: string;
            /** Target Price Minor */
            target_price_minor: number | null;
            /** Percentile Threshold */
            percentile_threshold: number | null;
            /** Percentile Window Days */
            percentile_window_days: number | null;
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "archived" | "bought";
            /** Bought Price Minor */
            bought_price_minor: number | null;
            /** Notes */
            notes: string | null;
            /** Alert Kinds Disabled */
            alert_kinds_disabled?: string[];
            /** Muted Until */
            muted_until: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            stats: components["schemas"]["BookStatsOut"];
        };
        /** BookPatch */
        BookPatch: {
            /** Target Price Minor */
            target_price_minor?: number | null;
            /** Percentile Threshold */
            percentile_threshold?: number | null;
            /** Percentile Window Days */
            percentile_window_days?: number | null;
            /** Status */
            status?: ("active" | "archived" | "bought") | null;
            /** Muted Until */
            muted_until?: string | null;
            /** Notes */
            notes?: string | null;
            /** Alert Kinds Disabled */
            alert_kinds_disabled?: string[] | null;
        };
        /**
         * BookStatsOut
         * @description Wire mirror of `book_alerter.stats.BookStats`.
         *
         *     Excludes `sorted_totals` (internal percentile cache).
         */
        BookStatsOut: {
            /** Book Id */
            book_id: number;
            /** Current Best Total Minor */
            current_best_total_minor: number | null;
            /** Current Best Price Minor */
            current_best_price_minor: number | null;
            /** Current Best Shipping Minor */
            current_best_shipping_minor: number | null;
            /** Current Best Source */
            current_best_source: string | null;
            /** Current Best Seller */
            current_best_seller: string | null;
            /** Current Best Condition */
            current_best_condition: string | null;
            /** Current Best Url */
            current_best_url: string | null;
            /** P25 Total Minor */
            p25_total_minor: number | null;
            /** P50 Total Minor */
            p50_total_minor: number | null;
            /** P75 Total Minor */
            p75_total_minor: number | null;
            /** All Time Min Total Minor */
            all_time_min_total_minor: number | null;
            /** All Time Max Total Minor */
            all_time_max_total_minor: number | null;
            /** Observation Count */
            observation_count: number;
            /** Days Of History */
            days_of_history: number;
            /** Last Observed At */
            last_observed_at: string | null;
            /** Percentile Window Days */
            percentile_window_days: number;
            /** Current Percentile Rank */
            current_percentile_rank: number | null;
            /** Current Effective Total Minor */
            current_effective_total_minor: number | null;
            /** Shipping Estimate Minor */
            shipping_estimate_minor: number | null;
        };
        /** ConfigDiff */
        ConfigDiff: {
            /** Added */
            added?: {
                [key: string]: unknown;
            };
            /** Removed */
            removed?: {
                [key: string]: unknown;
            };
            /** Changed */
            changed?: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
        };
        /**
         * ConfigUpdate
         * @description Request body for `PUT /api/config`.
         *
         *     `config` is the raw config dict — `Config.model_validate` does the heavy
         *     lifting (typed validation, defaults, env substitution is NOT re-run here,
         *     since the body is already the materialized config).
         */
        ConfigUpdate: {
            /** Config */
            config: {
                [key: string]: unknown;
            };
            /**
             * Dry Run
             * @default false
             */
            dry_run: boolean;
        };
        /** ConfigUpdateResult */
        ConfigUpdateResult: {
            diff: components["schemas"]["ConfigDiff"];
            /** Applied */
            applied: boolean;
            /** Errors */
            errors?: string[] | null;
        };
        /** DismissAllResult */
        DismissAllResult: {
            /** Dismissed Count */
            dismissed_count: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * NotificationTestResult
         * @description Result of `POST /api/notifications/{channel}/test`.
         */
        NotificationTestResult: {
            /** Channel */
            channel: string;
            /**
             * Status
             * @enum {string}
             */
            status: "sent" | "error";
            /** Error Message */
            error_message: string | null;
            alert: components["schemas"]["AlertOut"];
        };
        /**
         * ObservationsPage
         * @description Cursor-paginated page of price observations (newest-first).
         *
         *     `next_before` is the `observed_at` (ISO 8601) of the last row in `items`;
         *     pass it as the `before` query param to fetch the next page. `None` when
         *     `len(items) < limit` (i.e., the page is not full → no more rows).
         */
        ObservationsPage: {
            /** Items */
            items: components["schemas"]["PriceObservationOut"][];
            /** Next Before */
            next_before: string | null;
        };
        /**
         * PriceObservationOut
         * @description Wire mirror of `book_alerter.db.models.PriceObservation`.
         *
         *     Excludes the internal `raw` source payload and the `is_duplicate_of`
         *     dedup pointer — the observations endpoint filters duplicates out before
         *     serializing, so the pointer is irrelevant to callers.
         */
        PriceObservationOut: {
            /** Id */
            id: number;
            /** Book Id */
            book_id: number;
            /** Source */
            source: string;
            /** Seller */
            seller: string | null;
            /** Condition */
            condition: string;
            /** Price Minor */
            price_minor: number;
            /** Currency */
            currency: string;
            /** Shipping Minor */
            shipping_minor: number | null;
            /** Total Minor */
            total_minor: number;
            /** Url */
            url: string;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
        };
        /**
         * RefetchResult
         * @description Result of `POST /api/books/{id}/refetch`.
         *
         *     Fans out across every configured source. `triggered` lists sources whose
         *     `scheduler.trigger_now` returned a real `run_id`. `skipped` records sources
         *     that were intentionally not triggered: `reason="disabled"` for sources with
         *     `enabled=False` in config, `reason="backoff_active"` when the scheduler
         *     returned `0` (backoff gate). Empty `cfg.sources` yields two empty lists.
         */
        RefetchResult: {
            /** Triggered */
            triggered: components["schemas"]["RefetchTriggered"][];
            /** Skipped */
            skipped: components["schemas"]["RefetchSkipped"][];
        };
        /** RefetchSkipped */
        RefetchSkipped: {
            /** Source */
            source: string;
            /**
             * Reason
             * @enum {string}
             */
            reason: "disabled" | "backoff_active";
        };
        /** RefetchTriggered */
        RefetchTriggered: {
            /** Source */
            source: string;
            /** Run Id */
            run_id: number;
        };
        /**
         * SourceConfigOut
         * @description Wire mirror of `book_alerter.config.SourceConfig`.
         */
        SourceConfigOut: {
            /** Enabled */
            enabled: boolean;
            /** Region */
            region: string;
            /** Schedule */
            schedule: string;
            /** Jitter Seconds */
            jitter_seconds: number;
            /** Per Book Delay Seconds */
            per_book_delay_seconds: [
                number,
                number
            ];
            /** Concurrency */
            concurrency: number;
            /** Timeout Seconds */
            timeout_seconds: number;
            /** Max Consecutive Errors */
            max_consecutive_errors: number;
        };
        /**
         * SourcePatch
         * @description Partial update to a `SourceConfig`. `None` means "don't change".
         *
         *     `per_book_delay_seconds` accepts a 2-tuple `(min, max)` matching the YAML
         *     shape on `SourceConfig`. `jitter_seconds` is a non-negative scalar.
         */
        SourcePatch: {
            /** Enabled */
            enabled?: boolean | null;
            /** Schedule */
            schedule?: string | null;
            /** Concurrency */
            concurrency?: number | null;
            /** Jitter Seconds */
            jitter_seconds?: number | null;
            /** Per Book Delay Seconds */
            per_book_delay_seconds?: [
                number,
                number
            ] | null;
        };
        /**
         * SourceRunOut
         * @description Wire mirror of `book_alerter.db.models.SourceRun`.
         *
         *     Excludes `error_traceback` — debugging-only, can be very large; surface
         *     via structured logs (`source.run.exception`) rather than the API.
         */
        SourceRunOut: {
            /** Id */
            id: number;
            /** Source */
            source: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "success" | "error" | "partial";
            /** Books Attempted */
            books_attempted: number;
            /** Books Succeeded */
            books_succeeded: number;
            /** Error Message */
            error_message: string | null;
        };
        /** SourceStatusOut */
        SourceStatusOut: {
            /** Name */
            name: string;
            config: components["schemas"]["SourceConfigOut"];
            last_run: components["schemas"]["SourceRunOut"] | null;
        };
        /** TriggerRunResult */
        TriggerRunResult: {
            /** Run Id */
            run_id: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_books_api_books_get: {
        parameters: {
            query?: {
                include_archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_book_api_books_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_book_api_books__book_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_book_api_books__book_id__delete: {
        parameters: {
            query?: {
                hard?: boolean;
            };
            header?: never;
            path: {
                book_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_book_api_books__book_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_observations_api_books__book_id__observations_get: {
        parameters: {
            query?: {
                limit?: number;
                before?: string | null;
                source?: string | null;
            };
            header?: never;
            path: {
                book_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObservationsPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refetch_book_api_books__book_id__refetch_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefetchResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_book_stats_api_books__book_id__stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookStatsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    keepa_backfill_api_books__book_id__keepa_backfill_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_keepa_chart_api_books__book_id__keepa_chart_png_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_alerts_api_alerts_get: {
        parameters: {
            query?: {
                limit?: number;
                before?: string | null;
                kind?: ("new_low" | "target_hit" | "percentile_cross") | null;
                dismissed?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertsPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dismiss_alert_api_alerts__alert_id__dismiss_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dismiss_all_alerts_api_alerts_dismiss_all_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DismissAllResult"];
                };
            };
        };
    };
    list_sources_api_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceStatusOut"][];
                };
            };
        };
    };
    list_source_runs_api_sources__name__runs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceRunOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_source_run_api_sources__name__run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TriggerRunResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_source_api_sources__name__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourcePatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceStatusOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_config_api_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    put_config_api_config_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigUpdateResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_config_schema_api_config_schema_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    get_metadata_lookup_api_metadata_lookup_get: {
        parameters: {
            query: {
                /** @description Raw ISBN-10 or ISBN-13 */
                isbn: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookMetadata"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_metadata_search_api_metadata_search_get: {
        parameters: {
            query: {
                /** @description Free-text title/author query */
                q: string;
                /** @description Max results (Google Books cap is 40) */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookMetadataWithIsbn"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_notification_api_notifications__channel__test_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channel: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationTestResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
