"""create price_observation table

Revision ID: 30c98243f802
Revises: b0b34b4456fa
Create Date: 2026-05-14 09:41:45.655603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '30c98243f802'
down_revision: Union[str, Sequence[str], None] = 'b0b34b4456fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('priceobservation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('seller', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('condition', sa.String(), nullable=False),
    sa.Column('price_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('shipping_minor', sa.Integer(), nullable=True),
    sa.Column('total_minor', sa.Integer(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.Column('is_duplicate_of', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['is_duplicate_of'], ['priceobservation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('priceobservation', schema=None) as batch_op:
        batch_op.create_index('ix_obs_book_observed', ['book_id', 'observed_at'], unique=False)
        batch_op.create_index('ix_obs_book_source_observed', ['book_id', 'source', 'observed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_priceobservation_book_id'), ['book_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_priceobservation_observed_at'), ['observed_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('priceobservation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_priceobservation_observed_at'))
        batch_op.drop_index(batch_op.f('ix_priceobservation_book_id'))
        batch_op.drop_index('ix_obs_book_source_observed')
        batch_op.drop_index('ix_obs_book_observed')

    op.drop_table('priceobservation')
    # ### end Alembic commands ###
