"""create source_run, alert, notification_delivery, book_signal_state tables

Revision ID: 242d0f24dcef
Revises: 30c98243f802
Create Date: 2026-05-14 09:44:07.228291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '242d0f24dcef'
down_revision: Union[str, Sequence[str], None] = '30c98243f802'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sourcerun',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('books_attempted', sa.Integer(), nullable=False),
    sa.Column('books_succeeded', sa.Integer(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error_traceback', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('price_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('condition', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fired_at', sa.DateTime(), nullable=False),
    sa.Column('dismissed_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_via', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_book_id'), ['book_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_fired_at'), ['fired_at'], unique=False)

    op.create_table('booksignalstate',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('last_signal', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_all_time_min_total_minor', sa.Integer(), nullable=True),
    sa.Column('last_evaluated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('book_id')
    )
    op.create_table('notificationdelivery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('channel', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alert.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notificationdelivery', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notificationdelivery_alert_id'), ['alert_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notificationdelivery', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notificationdelivery_alert_id'))

    op.drop_table('notificationdelivery')
    op.drop_table('booksignalstate')
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_fired_at'))
        batch_op.drop_index(batch_op.f('ix_alert_book_id'))

    op.drop_table('alert')
    op.drop_table('sourcerun')
    # ### end Alembic commands ###
